package com.advancedb.addEmp;

/**
 * @author Roger Cruz
 * 11/28/2018
 * 
 * This class will control the Add Customer Screen.
 * 
 * */

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.Node;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

public class AddEmployeeController {
	@FXML
	private TextField firstName;
	@FXML
	private TextField LastName;
	@FXML
	private TextField Phone;
	@FXML
	private TextField email;

	// Event Listener on Button.onAction
	@FXML
	protected void addEmpToDB(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	protected void exitAddEmpScreen(ActionEvent e) {
		final Node source = (Node) e.getSource();
	    final Stage stage = (Stage) source.getScene().getWindow();
	    stage.close();
	}
}
