package com.advancedb.manageCustomer;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import java.sql.SQLException;

import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

public class manageCustomerController {
	@FXML
	private TextField phone;
	@FXML
	private TableView tableView;

	
	@FXML
	public void initialize() throws ClassNotFoundException, SQLException
	{
		
	}
	
	// Event Listener on Button.onAction
	@FXML
	public void updateCustomer(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void deactivateCustomer(ActionEvent event) {
		// TODO Autogenerated
	}
}
