package com.advancedb.manageInventory;

/**
 * @author Padmaja Parise
 * 12/8/2018
 * 
 * This class will control the Manage Inventory Screen.
 * 
 * */
import javafx.fxml.FXML;
import javafx.scene.control.TextField;
import java.sql.SQLException;
import java.util.ArrayList;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.scene.control.TableView;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import com.advancedb.utilClasses.Inventory;

public class manageInventoryController {
	@FXML
	private TextField shoesize;
	@FXML
	private TableView tableView;

	
	@FXML
	public void initialize() throws ClassNotFoundException, SQLException
	{
		
	}
	
	public void loadAllInventory() throws Exception
	{
		Inventory shoe = new Inventory();
		
		Configuration con = new Configuration().configure().addAnnotatedClass(Inventory.class);
		
		SessionFactory sf = con.buildSessionFactory();
		
		Session session = sf.openSession();
		
		Transaction tx = session.beginTransaction();		
		
		ObservableList<Inventory> observList = (ObservableList<Inventory>) new ArrayList();
		
		//observList = session.get
		get();
		
		tx.commit();
		
		//inventoryAdded(event);
	}
	
	// Event Listener on Button.onAction
	@FXML
	public void updateInventory(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void retireInventory(ActionEvent event) {
		// TODO Autogenerated
	}
		
	
	// Retrieving data 
		public static ArrayList<String> get() throws Exception{
			try {
				Connection con = getConnection();
				PreparedStatement statement = con.prepareStatement("SELECT * FROM shoes");
				
				ResultSet result = statement.executeQuery();
				
				ArrayList<String> array = new ArrayList<String>();
				while(result.next()) {
					array.add(result.getString("shoes_shoeID"));
					System.out.println("1st record accessed!\n");
					array.add(result.getString("shoes_shoeID"));
				}
				System.out.println("All records have been selected!\n");
				return array;			
			}catch(Exception e) {System.out.println(e);}
			return null;		
		}

		// Connecting to MySQL 
		public static Connection getConnection() throws Exception{	
			// TODO Auto-generated method stub
			try {			
				String url = "jdbc:mysql://localhost:3306/shoes?useSSL=false";
				String user = "root";
				String pass = "";
				Connection conn = DriverManager.getConnection(url,user,pass);
				System.out.println("Connecting to MySQL: established");
				return conn;
			}catch(Exception e) {
				System.out.println(e);
			}
			return null;
		}
		
}
